name: Trigger Build Scenarios
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  call_build:
    uses: ./.github/workflows/build-individual-scenarios.yaml
    strategy:
      fail-fast: false
      matrix:
        scenario_type: ["clash"]
        language: ["en", "pl"]
    with:
      scenario_type: ${{ matrix.scenario_type }}
      language: ${{ matrix.language }}
